[build]
  # We run from root, cd into client, build, and publish the result
  publish = "client/dist"
  command = "cd client && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
