name = "dietary-app-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# API Keys will be set via `wrangler secret put` or dashboard
# GEMINI_API_KEY = ""
# JWT_SECRET = ""

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "dietary-app-db"
database_id = "339415c0-c57c-48b5-9602-3407b3de9e29" # User will need to run `wrangler d1 create` to get this, or we use a placeholder for now and local dev works without it for `wrangler dev`
# preview_database_id = "DB" 

[observability]
enabled = true
